# Site settings
title: JC - Lost in the DevOps
email: jccastillocano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jcastillocano.github.io" # the base hostname & protocol for your site
twitter_username: jccastillocano
github_username:  jcastillocano
github_enterprise:  jccastillocano
linkedin_username: juan-carlos-castillo-cano-63698310
linkedin_name: Juan Carlos

# Build settings
markdown: kramdown

# Github config
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
